
from .base import *

DEBUG = False

ALLOWED_HOSTS = ['www.spacextrack.com']

# Security

SECURE_SSL_REDIRECT = True

SECURE_HSTS_SECONDS = 63072000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True