# Generated by Django 3.2.3 on 2021-05-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('launchpads', '0009_alter_launchpadimage_launchpad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('fairings', models.JSONField()),
                ('links', models.JSONField()),
                ('tbd', models.BooleanField()),
                ('net', models.BooleanField()),
                ('window', models.IntegerField()),
                ('success', models.BooleanField()),
                ('details', models.TextField()),
                ('auto_update', models.BooleanField()),
                ('launch_library_id', models.CharField(max_length=100, null=True)),
                ('flight_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('upcoming', models.BooleanField()),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('launchpad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='launchpads.launchpad')),
            ],
        ),
    ]
