# Generated by Django 3.2.3 on 2021-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
