# Generated by Django 3.2.3 on 2021-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0002_alter_launch_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='fairings',
            field=models.JSONField(null=True),
        ),
    ]
