# Generated by Django 3.2.3 on 2021-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0003_alter_launch_fairings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='window',
            field=models.IntegerField(null=True),
        ),
    ]
