# Generated by Django 3.2.3 on 2021-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0004_alter_launch_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='success',
            field=models.BooleanField(null=True),
        ),
    ]
