# Generated by Django 3.2.3 on 2021-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0006_auto_20210523_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='datetime_precision',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
