# Generated by Django 3.2.3 on 2021-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0007_alter_launch_datetime_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='static_fire_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
