# Generated by Django 3.2.3 on 2021-05-24 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0002_rename_booster_rocket_boosters'),
        ('launches', '0008_alter_launch_static_fire_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rockets.rocket'),
        ),
    ]
