# Generated by Django 3.2.3 on 2021-05-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0010_alter_launch_datetime_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='datetime_utc',
            field=models.DateTimeField(null=True),
        ),
    ]
