# Generated by Django 3.2.3 on 2021-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0011_alter_launch_datetime_utc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='datetime_local',
            new_name='date_local',
        ),
        migrations.RenameField(
            model_name='launch',
            old_name='datetime_precision',
            new_name='date_precision',
        ),
        migrations.RenameField(
            model_name='launch',
            old_name='datetime_utc',
            new_name='date_unix',
        ),
        migrations.RenameField(
            model_name='launch',
            old_name='static_fire_datetime',
            new_name='static_fire_date_utc',
        ),
        migrations.AddField(
            model_name='launch',
            name='date_utc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='static_fire_date_unix',
            field=models.DateTimeField(null=True),
        ),
    ]
