# Generated by Django 3.2.3 on 2021-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0012_auto_20210524_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='date_unix',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='static_fire_date_unix',
            field=models.IntegerField(null=True),
        ),
    ]
