# Generated by Django 3.2.3 on 2021-05-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0012_launchpad_rockets'),
        ('launches', '0013_auto_20210524_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launchpad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='launchpads.launchpad'),
        ),
    ]
