# Generated by Django 3.2.3 on 2021-05-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0012_launchpad_rockets'),
        ('rockets', '0002_rename_booster_rocket_boosters'),
        ('launches', '0014_alter_launch_launchpad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launchpad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launchpads.launchpad'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rockets.rocket'),
        ),
    ]
