# Generated by Django 3.1.2 on 2021-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launchpad',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('latitiude', models.IntegerField()),
                ('logitude', models.IntegerField()),
                ('details', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Launchpad',
                'verbose_name_plural': 'Launchpads',
            },
        ),
    ]
