# Generated by Django 3.2.3 on 2021-05-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0002_launchpad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launchpad',
            old_name='latitiude',
            new_name='latitude',
        ),
    ]
