# Generated by Django 3.2.3 on 2021-05-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0003_rename_latitiude_launchpad_latitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launchpad',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
