# Generated by Django 3.2.3 on 2021-05-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0005_auto_20210523_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchpad',
            name='launch_attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='launchpad',
            name='launch_successes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
