# Generated by Django 3.2.3 on 2021-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0006_auto_20210523_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchpad',
            name='sanitized_name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
