# Generated by Django 3.2.3 on 2021-05-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0007_launchpad_sanitized_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchpadimage',
            name='site_id',
        ),
        migrations.AddField(
            model_name='launchpadimage',
            name='launchpad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='launchpads.launchpad'),
        ),
    ]
