# Generated by Django 3.2.3 on 2021-05-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0008_auto_20210523_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpadimage',
            name='launchpad',
            field=models.ForeignKey(default='remove me', on_delete=django.db.models.deletion.DO_NOTHING, to='launchpads.launchpad'),
            preserve_default=False,
        ),
    ]
