# Generated by Django 3.2.3 on 2021-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0009_alter_launchpadimage_launchpad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
