# Generated by Django 3.2.3 on 2021-05-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpads', '0010_alter_launchpad_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='details',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
