# Generated by Django 3.2.3 on 2021-05-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0002_rename_booster_rocket_boosters'),
        ('launchpads', '0011_alter_launchpad_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchpad',
            name='rockets',
            field=models.ManyToManyField(to='rockets.Rocket'),
        ),
    ]
