# Generated by Django 3.2.3 on 2021-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0002_rename_booster_rocket_boosters'),
        ('launchpads', '0013_alter_launchpadimage_launchpad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='rockets',
            field=models.ManyToManyField(null=True, to='rockets.Rocket'),
        ),
    ]
