version: '3.3'

services:
  intermediate-caching-service:
    build: ./intermediate-caching-api
  gunicorn-service:
    build: ./
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/run/
      - type: bind
        source: ../database
        target: /usr/src/app/database/
    ports:
      - 5900:8000
    environment:
      - DJANGO_SETTINGS_MODULE=space_django.settings.production
    command: gunicorn space_django.wsgi:application --name space_django --bind=unix:/usr/src/app/run/gunicorn.sock --workers 1
    depends_on:
      - intermediate-caching-service