version: '3'

services:
  intermediate-caching-service:
    build: ./intermediate-caching-api
    volumes: 
      - ./intermediate-caching-api:/usr/src/app
  website:
    build: ./
    ports:
      - 5900:8000
    depends_on:
      - intermediate-caching-service