version: '3.3'

services:
  intermediate-caching-service:
    build: ./intermediate-caching-api
    volumes: 
      - ./intermediate-caching-api:/usr/src/app
  gunicorn-service:
    build: ./
    volumes:
      - ./:/usr/src/app
      - type: bind
        source: ./
        target: /usr/src/app/run/
    ports:
      - 5900:8000
    environment:
      - DJANGO_SETTINGS_MODULE=space_django.settings.production
    command: gunicorn space_django.wsgi:application --name space_django --bind=unix:/usr/src/app/run/gunicorn.sock --workers 3
    depends_on:
      - intermediate-caching-service