# Generated by Django 2.2.6 on 2019-11-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Significat_Launch',
            new_name='Significant_Launch',
        ),
    ]
