# Generated by Django 2.2.6 on 2019-11-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191111_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Significant_Launch',
            new_name='SignificantLaunch',
        ),
    ]
