# Generated by Django 2.2.6 on 2019-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191111_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='significantlaunch',
            options={'verbose_name': 'Significant Launch', 'verbose_name_plural': 'Significant Launches'},
        ),
    ]
