# Generated by Django 2.2.6 on 2019-10-23 13:39

from django.db import migrations, models
import utils.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('response', utils.db.fields.JSONField()),
                ('timestamp', models.DateTimeField(verbose_name='request timestamp')),
            ],
        ),
    ]
