# Generated by Django 2.2.6 on 2019-10-23 11:49

from django.db import migrations
import interapi.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=interapi.db.fields.DictField(),
        ),
    ]
