# Generated by Django 2.2.6 on 2019-10-23 12:06

from django.db import migrations
import interapi.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interapi', '0002_auto_20191023_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=interapi.db.fields.JSONField(),
        ),
    ]
