# Generated by Django 3.2.3 on 2021-05-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rocket',
            old_name='booster',
            new_name='boosters',
        ),
    ]
