# Generated by Django 4.0.3 on 2022-04-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='launchpad',
        ),
        migrations.AddField(
            model_name='launchpad',
            name='launches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex.launch'),
        ),
    ]
