# Generated by Django 3.2.3 on 2021-05-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='rockets',
            field=models.ManyToManyField(null=True, to='spacex.Rocket'),
        ),
    ]
