# Generated by Django 3.2.3 on 2021-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('patch', 'Patch'), ('image', 'Image')], max_length=10),
        ),
    ]
