# Generated by Django 3.2.3 on 2021-05-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0002_alter_launchpad_rockets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignificantLaunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Significant Launch',
                'verbose_name_plural': 'Significant Launches',
            },
        ),
        migrations.AlterModelOptions(
            name='launch',
            options={'verbose_name_plural': 'launches'},
        ),
    ]
