# Generated by Django 3.2.3 on 2021-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0002_alter_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='source_url',
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.URLField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
