# Generated by Django 4.0.3 on 2022-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0002_remove_launch_launchpad_launchpad_launches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchpad',
            name='launches',
        ),
        migrations.AddField(
            model_name='launchpad',
            name='launches',
            field=models.ManyToManyField(to='spacex.launch'),
        ),
    ]
