# Generated by Django 3.2.3 on 2021-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0003_auto_20210527_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='sanitized_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
