# Generated by Django 3.2.3 on 2021-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0004_launch_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='images',
            field=models.ManyToManyField(null=True, to='spacex.Image'),
        ),
    ]
