# Generated by Django 4.0.3 on 2022-04-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0004_remove_launchpad_launches_launchpad_launches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchpad',
            name='launches',
        ),
        migrations.AddField(
            model_name='launch',
            name='launchpad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex.launchpad'),
        ),
    ]
