# Generated by Django 3.2.3 on 2021-05-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0004_rocket_sanitized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='significantlaunch',
            name='flight_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex.launch'),
        ),
    ]
