# Generated by Django 3.2.3 on 2021-05-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0005_alter_significantlaunch_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='significant',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SignificantLaunch',
        ),
    ]
