# Generated by Django 3.2.3 on 2021-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0006_alter_launch_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='etag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
