# Generated by Django 3.2.3 on 2021-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0007_launch_sanitized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpad',
            name='rockets',
            field=models.ManyToManyField(to='spacex.Rocket'),
        ),
    ]
