# Generated by Django 3.2.3 on 2021-06-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0007_image_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('patch', 'Patch'), ('image', 'Image'), ('portrait', 'Portrait')], max_length=10),
        ),
    ]
