# Generated by Django 3.2.3 on 2021-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0008_alter_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='images',
            field=models.ManyToManyField(to='spacex.Image'),
        ),
    ]
