# Generated by Django 3.2.3 on 2021-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0009_alter_launchpadimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpadimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
