# Generated by Django 3.2.3 on 2021-06-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0009_crew_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='images',
        ),
        migrations.AddField(
            model_name='crew',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex.image'),
        ),
    ]
