# Generated by Django 3.2.3 on 2021-06-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0010_auto_20210620_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='images',
        ),
        migrations.AddField(
            model_name='crew',
            name='images',
            field=models.ManyToManyField(to='spacex.Image'),
        ),
    ]
