# Generated by Django 3.2.3 on 2021-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0011_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='block',
            field=models.IntegerField(null=True),
        ),
    ]
