# Generated by Django 3.2.3 on 2021-06-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0012_auto_20210620_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
