# Generated by Django 3.2.3 on 2021-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0014_core_launches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landpad',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sanitized_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('landing_attempts', models.IntegerField()),
                ('landing_successes', models.IntegerField()),
                ('wikipedia', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Landpad',
                'verbose_name_plural': 'Landpads',
            },
        ),
    ]
