# Generated by Django 3.2.3 on 2021-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0015_landpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpad',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
