# Generated by Django 3.2.3 on 2021-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0016_landpad_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('dragon', models.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('sanitized_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('reused', models.BooleanField()),
                ('customers', models.JSONField()),
                ('norad_ids', models.JSONField()),
                ('nationalities', models.JSONField()),
                ('manufacturers', models.JSONField()),
                ('mass_kg', models.FloatField()),
                ('mass_lbs', models.FloatField()),
                ('orbit', models.CharField(max_length=100)),
                ('reference_system', models.CharField(max_length=100)),
                ('regime', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Payload',
                'verbose_name_plural': 'Payloads',
            },
        ),
    ]
