# Generated by Django 3.2.3 on 2021-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0017_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='mass_kg',
            field=models.FloatField(null=True),
        ),
    ]
