# Generated by Django 3.2.3 on 2021-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0018_alter_payload_mass_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='mass_lbs',
            field=models.FloatField(null=True),
        ),
    ]
