# Generated by Django 3.2.3 on 2021-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0020_alter_payload_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='reference_system',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
