# Generated by Django 3.2.3 on 2021-05-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0021_alter_payload_reference_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='orbit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
