# Generated by Django 3.2.3 on 2021-05-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0022_alter_payload_orbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='launch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex.launch'),
        ),
    ]
