# Generated by Django 3.2.3 on 2021-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0023_payload_launch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('heat_shield', models.JSONField()),
                ('launch_payload_mass', models.JSONField()),
                ('launch_payload_vol', models.JSONField()),
                ('return_payload_mass', models.JSONField()),
                ('return_payload_vol', models.JSONField()),
                ('pressurized_capsule', models.JSONField()),
                ('trunk', models.JSONField()),
                ('height_w_trunk', models.JSONField()),
                ('diameter', models.JSONField()),
                ('first_flight', models.DateField()),
                ('flickr_images', models.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('sanitized_name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('crew_capacity', models.IntegerField()),
                ('sidewall_angle_deg', models.IntegerField()),
                ('orbit_duration_yr', models.IntegerField()),
                ('dry_mass_kg', models.IntegerField()),
                ('dry_mass_lb', models.IntegerField()),
                ('thrusters', models.JSONField()),
                ('wikipedia', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dragon',
                'verbose_name_plural': 'Dragons',
            },
        ),
        migrations.AlterModelOptions(
            name='launch',
            options={'ordering': ['flight_number'], 'verbose_name': 'launch', 'verbose_name_plural': 'launches'},
        ),
    ]
