# Generated by Django 3.2.3 on 2021-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0024_auto_20210530_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sanitized_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('wikipedia', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crew',
            },
        ),
    ]
