# Generated by Django 3.2.3 on 2021-05-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0025_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='crew',
            field=models.ManyToManyField(to='spacex.Crew'),
        ),
    ]
