# Generated by Django 3.2.3 on 2021-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0027_crew_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='lifespan_years',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
