# Generated by Django 3.2.3 on 2021-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0028_payload_lifespan_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='lifespan_years',
            field=models.IntegerField(null=True),
        ),
    ]
